### PR TITLE
First release

### PR DESCRIPTION
**Pull request by SimonLab**
ref: #31 

Udate `mix.exs` values to add a description, the package property and the name of the package `ex_cid`

### CODE REVIEW

**Review by RobStallion — APPROVED** [review]
AMAZING!!! I don't know if I'm easily impressed or not but I am loving all this stuff lol. Really nice. 

One comment though. I noticed on the b58 readme you added a hex badge...
image

Should we add one of those to this readme as well?

**Review by nelsonic — APPROVED** [review]
@SimonLab :shipit:  (_badge in the `README.md` would be good too..._)

**Comment by SimonLab** [comment]
badge added:
image

Just need to publish the package and the badge will be happy.
@RobStallion do you want to publish it has I've done it with base58encoding already? Let me know and we can pair quickly on this and you'll be able to add your feedback to https://github.com/dwyl/learn-elixir#publishing

**Comment by RobStallion** [comment]
@SimonLab Yeah that would be cool. Let me know whenever you are free to do this 👍

**Pull request merged**
